In [1]:
import INN
import torch
import torch.nn as nn

In [4]:
model = INN.Sequential(INN.Nonlinear(dim=3, method='NICE'),
                       INN.BatchNorm1d(3),
                       INN.Nonlinear(dim=3, method='NICE'), INN.ResizeFeatures(3, 1))
model.eval()

x = torch.Tensor([[1,2,3],[4,5,6]])
y, logp, logdet = model(x)

In [8]:
model[-1].mu_var(y)

(tensor([[0., 0.],
         [0., 0.]], grad_fn=<AddmmBackward>), tensor([[1., 1.],
         [1., 1.]], grad_fn=<AddBackward0>), tensor([-0., -0.], grad_fn=<MulBackward0>))

In [ ]:
model.

In [19]:
model = INN.Sequential(INN.Conv1d(channels=3, kernel_size=3),
                       INN.BatchNorm1d(3),
                       INN.Conv1d(channels=3, kernel_size=3), INN.ResizeFeatures(3, 1))
model.eval()

model(torch.randn(2, 3, 10))

(tensor([[[-0.9920, -0.2657,  1.4083,  0.2213, -1.0507,  2.0254,  0.7112,
           -0.5681, -1.5983, -1.0722]],
 
         [[-0.0923, -0.2650,  0.1913,  0.2566, -0.2029,  1.2661, -1.0854,
            0.7446, -0.8261,  1.0681]]], grad_fn=<SliceBackward>),
 tensor([-29.1110, -26.3051], grad_fn=<AddBackward0>),
 tensor([-0.0002, -0.0002], grad_fn=<AddBackward0>))

In [21]:
model = INN.Sequential(INN.Conv2d(channels=3, kernel_size=3),
                       INN.BatchNorm2d(3),
                       INN.Conv2d(channels=3, kernel_size=3), INN.ResizeFeatures(3, 1))
model.eval()

model(torch.randn(2, 3, 10, 10))

(tensor([[[[ 8.7071e-01, -1.0464e-01,  1.8869e+00,  6.9060e-01, -6.1016e-01,
             7.2888e-01,  3.8579e-01,  2.2335e-01,  1.7959e+00,  9.0549e-01],
           [ 2.8548e-01, -3.1185e-01,  1.0732e-01, -1.5369e+00,  3.5932e+00,
             4.3840e-01,  9.0574e-01, -1.0931e+00,  1.4590e+00,  5.4487e-01],
           [ 6.4883e-01,  1.1075e+00,  1.0550e+00, -8.8358e-01,  9.2693e-01,
            -5.9010e-01, -9.1532e-01,  4.3711e-01,  3.1616e-01,  3.0101e-01],
           [ 5.5267e-02, -1.4526e+00,  1.5323e+00,  2.7392e+00,  9.4440e-01,
             4.0911e-01,  1.8262e+00,  6.6810e-01,  2.2713e+00,  8.9356e-01],
           [ 3.4218e-01,  2.2446e+00,  2.3920e+00, -1.4815e-01,  1.2369e+00,
             4.8425e-01,  2.4357e+00,  8.1294e-01,  1.8401e+00, -6.3576e-01],
           [ 1.4237e-01, -5.6217e-01,  1.0157e+00,  2.8890e-02, -8.4484e-01,
             2.2992e+00,  6.5947e-01,  3.2364e-01,  4.5920e-01,  1.1230e+00],
           [-5.0275e-01, -6.3960e-01,  1.0207e+00,  2.1764e-01,  1.071

In [2]:
model = INN.BatchNorm1d(3)#INN.Nonlinear(dim=3, method='iResNet', num_n=100, num_iter=50)

In [3]:
def linear_Jacobian_matrix(model, x):
    batch_size, dim = x.shape
    x.requires_grad = True
    model.computing_p(True)
    y, log_p, log_det = model(x)
    
    grad_list = []
    for i in range(dim):
        v = torch.zeros((batch_size, dim))
        v[:, i] = 1
        grad = INN.utilities.vjp(y, x, v)[0]
        grad_list.append(grad.detach())
    return torch.stack(grad_list, dim=1), log_det

In [4]:
def Jacobian_matrix(model, x):
    shape = x.shape
    dim = int(torch.prod(torch.Tensor(list(x.shape))).item())
    repeats = [dim]
    for i in range(len(x.shape)):
        repeats.append(1)
    
    x_hat = x.unsqueeze(0).repeat(tuple(repeats))
    x_hat.requires_grad = True
    model.computing_p(True)
    y, log_p, log_det = model(x_hat)
    
    v = torch.diag(torch.ones(dim)).reshape((dim, *x.shape))
    grad = INN.utilities.vjp(y, x_hat, v)[0]
    
    return grad.detach(), log_det.detach()

In [5]:
x = torch.randn(3)

In [10]:
model.eps = 1e-5
J, log_det = Jacobian_matrix(model, x)
J

tensor([[ 1.0207,  0.7147,  0.1159],
        [ 0.3893,  1.9171, -0.6180],
        [ 0.4169, -0.0570,  1.0998]])

In [11]:
torch.log(torch.abs(torch.det(J)))

tensor(0.4258)

In [12]:
torch.mean(log_det)

tensor(0.4258)

In [14]:
x = torch.randn((6, 3))

In [15]:
model.eval()
Js, log_det = linear_Jacobian_matrix(model, x)
real_log_det = torch.log(torch.abs(torch.det(Js)))

print(f'J_g={real_log_det},\nJ_c={log_det.detach()}')

J_g=tensor([ 1.9498, -0.0728,  1.3574,  0.7588,  1.3956,  0.7595]),
J_c=tensor([ 1.9498, -0.0728,  1.3574,  0.7588,  1.3956,  0.7595])


In [16]:
Js[0]

tensor([[ 1.9760, -1.3065,  1.2205],
        [ 0.5567, -0.8171, -1.6935],
        [ 0.0597,  2.1638,  2.1138]])

In [46]:
torch.sum(-1 * torch.log(torch.var(x, dim=0, unbiased=False) + model.eps) / 2)

tensor(0.7945, grad_fn=<SumBackward0>)

## Bug lists

1. `INN.BatchNorm1d()` fails on Jacobian tests [fixed]
2. `INN.iResNet()` has large differece to the ground-truth!

In [53]:
model = nn.BatchNorm1d(3, affine=False)

In [54]:
model.running_mean

tensor([0., 0., 0.])

In [55]:
model(x)

tensor([[-0.3725, -0.3559, -1.4208],
        [ 0.7690,  0.1532,  0.9104],
        [ 0.9525, -0.5532, -0.3847],
        [-2.0273,  0.2497,  1.6467],
        [ 0.4455,  1.8891, -0.3031],
        [ 0.2327, -1.3830, -0.4485]], grad_fn=<NativeBatchNormBackward>)

In [60]:
var = torch.var(x, dim=0, unbiased=False)
mean = torch.mean(x, dim=0)

(x - mean) / torch.sqrt(var + model.eps)

tensor([[-0.3725, -0.3559, -1.4208],
        [ 0.7690,  0.1532,  0.9104],
        [ 0.9525, -0.5532, -0.3847],
        [-2.0273,  0.2497,  1.6467],
        [ 0.4455,  1.8891, -0.3031],
        [ 0.2327, -1.3830, -0.4485]], grad_fn=<DivBackward0>)

In [17]:
x = torch.randn((5, 3))
bn = nn.BatchNorm1d(3, affine=False)

In [18]:
bn(x)

tensor([[-1.6941,  0.2933, -0.2451],
        [-0.1313, -0.2711,  1.4740],
        [ 0.2754, -0.2282,  0.4445],
        [ 0.1287, -1.4409, -0.0721],
        [ 1.4213,  1.6469, -1.6014]])

In [5]:
x = torch.randn((3,3,3))

In [29]:
list(x.shape)

[3, 3, 3]

In [26]:
x.shape = 5

AttributeError: attribute 'shape' of 'torch._C._TensorBase' objects is not writable

In [31]:
[1,2,3,4,5][4:]

[5]

# New Modules

## Conv1d

In [48]:
class _default_1d_coupling_function(nn.Module):
    def __init__(self, channels, kernel_size, activation_fn=nn.ReLU, w=4):
        super(_default_1d_coupling_function, self).__init__()
        if kernel_size % 2 != 1:
            raise ValueError(f'kernel_size must be an odd number, but got {kernel_size}')
        r = kernel_size // 2
        
        self.f = nn.Sequential(nn.Conv1d(channels, channels*w, kernel_size, padding=r),
                               activation_fn(),
                               nn.Conv1d(w*channels, w*channels, kernel_size, padding=r),
                               activation_fn(),
                               nn.Conv1d(w*channels, channels, kernel_size, padding=r)
                              )
    def forward(self, x):
        return self.f(x)

In [100]:
INNModule = INN.INNAbstract.INNModule

class CouplingConv(INNModule):
    '''
    General invertible covolution layer for coupling methods
    '''
    def __init__(self, num_feature, mask=None):
        super(CouplingConv, self).__init__()
        self.num_feature = num_feature
        if mask is None:
            self.mask = self._mask(num_feature)
        else:
            self.mask = mask
    
    def _mask(self, n):
        m = torch.zeros(n)
        m[:(n // 2)] = 1
        return m
    
    def working_mask(self, x):
        '''
        Generate feature mask for 1d inputs
        x.shape = [batch_size, feature, *]
        mask.shape = [1, feature, *(1)]
        '''
        batch_size, feature, *other = x.shape
        mask = self.mask.reshape(1, self.num_feature, *[1] * len(other))
        return mask


class CouplingConv1d(CouplingConv):
    '''
    General 1-d invertible convolution layer for coupling methods
    '''
    def __init__(self, num_feature, mask=None):
        super(CouplingConv1d, self).__init__(num_feature, mask=mask)


class Conv1dNICE(CouplingConv1d):
    '''
    1-d invertible convolution layer by NICE method
    '''
    def __init__(self, channels, kernel_size, w=4, activation_fn=nn.ReLU, m=None, mask=None):
        super(Conv1dNICE, self).__init__(num_feature=channels, mask=mask)
        if m is None:
            self.m = _default_1d_coupling_function(channels, kernel_size, activation_fn, w=w)
        else:
            self.m = m
    
    def forward(self, x):
        mask = self.working_mask(x)
        
        x_ = mask * x
        x = x + (1-mask) * self.m(x_)
        
        x_ = (1-mask) * x
        x = x + mask * self.m(x_)
        return x
    
    def inverse(self, y):
        mask = self.working_mask(y)
        
        y_ = (1-mask) * y
        y = y - mask * self.m(y_)
        
        y_ = mask * y
        y = y - (1-mask) * self.m(y_)
        
        return y
    
    def logdet(self, **args):
        return 0


class Conv1dNVP(CouplingConv1d):
    '''
    1-d invertible convolution layer by NICE method
    TODO: inverse error is too large
    '''
    def __init__(self, channels, kernel_size, w=4, activation_fn=nn.ReLU, s=None, t=None, mask=None):
        super(Conv1dNVP, self).__init__(num_feature=channels, mask=mask)
        if s is None:
            self.log_s = _default_1d_coupling_function(channels, kernel_size, activation_fn, w=w)
        else:
            self.log_s = s
        
        if t is None:
            self.t = _default_1d_coupling_function(channels, kernel_size, activation_fn, w=w)
        else:
            self.t = t
    
    def s(self, x):
        return torch.exp(self.log_s(x))
    
    def forward(self, x):
        mask = self.working_mask(x)
        
        x_ = mask * x
        x = (1-mask) * (self.s(x_) * x + self.t(x_)) + x_
        
        mask = 1 - mask
        x_ = mask * x
        x = (1-mask) * (self.s(x_) * x + self.t(x_)) + x_
        
        return x
    
    def inverse(self, y):
        mask = 1 - self.working_mask(y)
        
        y_ = mask * y
        y = (1-mask) * (y - self.t(y_)) / torch.exp(self.log_s(y_)) + y_
        
        mask = 1 - mask
        y_ = mask * y
        y = (1-mask) * (y - self.t(y_)) / torch.exp(self.log_s(y_)) + y_
        
        return y
    
    def logdet(self, **args):
        return 0

In [2]:
import INN
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
x = torch.randn((3, 5, 8)) * 10

model = INN.Linear1d(5)

In [3]:
model(x)

(tensor([[[-4.5962e-01, -8.3237e-01, -5.2095e+00, -6.3192e+00, -9.2027e+00,
           -2.3169e+01, -2.2931e+00, -1.5648e+00],
          [ 2.1111e+00,  4.1545e+00, -4.4625e+00,  9.5212e+00,  4.8327e+00,
            8.9690e+00, -2.5365e+01, -1.0859e+01],
          [-3.9164e+00,  1.7029e+01,  4.7630e+00,  1.9899e+01, -2.3675e+01,
           -5.6664e+00,  1.8262e+01,  4.9501e+00],
          [ 3.7490e+00, -1.3335e+00,  3.8716e+00,  1.2091e+01, -2.0418e+00,
           -1.1282e+01,  1.1244e+00, -9.5155e-01],
          [ 2.0400e+00,  1.3096e+01, -4.2499e-01,  3.8104e+00, -9.6784e+00,
            1.1031e+01,  6.2131e+00, -1.5430e+01]],
 
         [[ 1.3582e+01, -1.9608e+01, -4.0115e+00,  1.2407e+00, -8.5277e+00,
            7.0188e+00, -7.1900e+00, -1.7199e+00],
          [-5.4620e+00, -9.5898e+00,  5.4368e+00,  2.3484e+00, -1.3124e+01,
           -4.8956e+00, -2.5614e+00,  3.3316e+00],
          [-3.0688e+00, -1.9365e-01, -4.9798e+00,  2.3397e+00,  1.3315e+01,
           -4.1992e-01,  1.6362e

In [42]:
logdet

tensor([17.2584,  8.3290, 27.7419], grad_fn=<AddBackward0>)

In [43]:
nn.L1Loss()(model.inverse(y), x)

tensor(9.3338, grad_fn=<L1LossBackward>)

In [47]:
model.inverse(y) - x

tensor([[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00,  0.0000e+00, -5.9605e-08],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00,  0.0000e+00, -4.7684e-07],
         [-1.9073e-06, -2.3842e-07,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 2.0160e+00,  4.5725e+00, -6.5988e+00, -6.9353e+00, -1.9093e+01,
           6.4344e+00,  4.9652e+00, -9.1800e+00],
         [-5.2022e+00, -1.6432e+01, -1.0714e+00,  3.1963e+01, -4.8019e+01,
          -2.0962e+02, -1.3407e-02,  1.0146e+01],
         [-3.1409e-01, -8.2552e+00, -7.9736e+00,  2.8125e+00,  1.7196e+01,
          -1.2859e+01, -4.4796e+00, -1.7652e+00]

In [74]:
mat = INN.utilities.PLUMatrix(5)
mat.cuda()

PLUMatrix()

In [71]:
weight = mat.W().unsqueeze(-1)
F.conv1d(x, weight).shape

torch.Size([3, 5, 8])

In [73]:
x.shape

torch.Size([3, 5, 8])

In [75]:
mat.W()

tensor([[ 0.6578, -0.3593,  0.5535, -0.2352, -0.2766],
        [-0.4351, -0.4065, -0.1952, -0.1574, -0.7633],
        [ 0.2616, -0.7114, -0.5362,  0.1648,  0.3330],
        [-0.1821, -0.0787, -0.0500, -0.9152,  0.3472],
        [ 0.5258,  0.4398, -0.6046, -0.2349, -0.3309]], device='cuda:0',
       grad_fn=<MmBackward>)

In [80]:
class Conv1d1x1(nn.Module):
    def __init__(self, num_feature, mat=None):
        super(Conv1d1x1, self).__init__()
        if mat is None:
            self.mat = INN.utilities.PLUMatrix(num_feature)
        else:
            self.mat = mat
    
    def weight(self):
        return self.mat.W().unsqueeze(-1)
    
    def weight_inv(self):
        return self.mat.inv_W().unsqueeze(-1)
    
    def forward(self, x, log_p0=0, log_det_J=0):
        return F.conv1d(x, self.weight())
    
    def inverse(self, y):
        return F.conv1d(y, self.weight_inv())

In [81]:
model = Conv1d1x1(5)

In [82]:
y = model(x).detach()

In [85]:
model.inverse(y) - x

tensor([[[ 9.5367e-07, -7.7486e-07,  0.0000e+00, -2.5034e-06,  0.0000e+00,
           1.0729e-06, -1.9073e-06,  5.3644e-07],
         [-1.9073e-06,  9.5367e-07,  9.5367e-07,  2.8610e-06,  0.0000e+00,
          -1.9073e-06,  1.9073e-06, -2.3842e-07],
         [ 0.0000e+00,  0.0000e+00,  4.7684e-07,  0.0000e+00, -1.9073e-06,
           0.0000e+00,  3.5763e-07, -9.5367e-07],
         [-3.8147e-06,  0.0000e+00,  0.0000e+00,  1.9073e-06,  3.8147e-06,
          -4.7684e-07,  0.0000e+00, -1.1921e-07],
         [-1.6689e-06, -9.5367e-07,  4.7684e-07,  0.0000e+00,  4.7684e-07,
           9.5367e-07, -1.9073e-06,  1.4305e-06]],

        [[-7.1526e-07,  1.9073e-06,  4.7684e-07, -1.4305e-06,  0.0000e+00,
           2.3842e-06, -1.4305e-06,  0.0000e+00],
         [ 0.0000e+00,  9.5367e-07, -4.7684e-07, -2.6226e-06, -1.9073e-06,
          -1.9073e-06,  9.5367e-07, -1.4305e-06],
         [ 0.0000e+00,  0.0000e+00,  9.5367e-07,  1.9073e-06,  0.0000e+00,
           4.7684e-07, -4.7684e-07,  4.7684e-07]

In [6]:
nn.Conv2d(5, 5, 1).weight.shape

torch.Size([5, 5, 1, 1])

## Reshape

In [1]:
import INN
import torch
import torch.nn as nn
import torch.nn.functional as F

In [54]:
x = torch.randn((3, 5, 8))
model = INN.Sequential(INN.Conv1d(5, 3),
                       INN.BatchNorm1d(5),
                       INN.PixelShuffle1d(2), 
                       INN.Conv1d(10, 3),
                       INN.BatchNorm1d(10),
                       INN.Linear1d(10),
                       INN.ResizeFeatures(10, 5),
                       
                       INN.PixelShuffle1d(2),
                       INN.Conv1d(10, 3),
                       INN.BatchNorm1d(10),
                       INN.Linear1d(10),
                       INN.ResizeFeatures(10, 5),
                       INN.PixelShuffle1d(2),
                       INN.Reshape((10,1), (10,)),
                      
                       INN.BatchNorm1d(10),
                       INN.Nonlinear(10),
                       INN.ResizeFeatures(10, 8),
                       INN.BatchNorm1d(8),
                       INN.Nonlinear(8)
                      )
model.computing_p(False)
model.eval()
''

''

In [55]:
y = model.inverse(model(x))

In [66]:
dist = torch.distributions.laplace.Laplace(0, 1)

In [68]:
dist.log_prob(dist.sample((3,3)))

tensor([[-2.0021, -1.1280, -1.8641],
        [-1.4805, -1.9972, -1.0846],
        [-3.1994, -1.2627, -2.5235]])

In [71]:
dist.sample((3,))

tensor([-2.1263,  0.4390,  0.8940])

In [53]:
torch.randn(1) * torch.ones(5)

tensor([0.3992, 0.3992, 0.3992, 0.3992, 0.3992])

In [78]:
torch.nn.init.kaiming_normal_(nn.Conv1d(3,3,3).weight.data)

tensor([[[-0.3525, -0.6182,  0.0608],
         [-0.2099, -0.7171, -0.2537],
         [ 0.2056,  0.3083,  0.1566]],

        [[ 0.2923,  0.3576,  0.6361],
         [ 0.5877,  0.2804, -1.3565],
         [-0.4057,  0.0572,  0.4639]],

        [[-0.1204,  0.1078, -0.3653],
         [ 0.1686,  0.6474,  0.1929],
         [-0.1860, -0.1333,  0.0967]]])

In [111]:
x = torch.randn((3, 5, 8))

In [115]:
var = torch.var(x, dim=1, unbiased=False, keepdim=True)
mean = torch.mean(x, dim=1, keepdim=True)
y = (x-mean) / torch.sqrt(var)

In [112]:
torch.var(x, dim=0, unbiased=False, keepdim=True)

tensor([[[1.2872, 0.2362, 0.2864, 1.8388, 0.5417, 0.3461, 0.3637, 0.0270],
         [0.0376, 0.2273, 0.2307, 3.1640, 0.5205, 0.8906, 0.6774, 0.1006],
         [0.8270, 0.0053, 0.1850, 0.3851, 0.4486, 0.4170, 0.0254, 0.1880],
         [0.9127, 0.1060, 0.1569, 0.5217, 0.3434, 0.4291, 1.1008, 1.7872],
         [1.5368, 0.0630, 0.0488, 0.6278, 0.2728, 0.4753, 0.3533, 0.0304]]])

In [116]:
y0 = nn.BatchNorm1d(5)(x)

In [123]:
import torch
from torch.autograd import Variable

grad_list = []

def print_grad(grad):
    print(grad)
    grad_list.append(grad)

x = Variable(torch.randn(2, 1), requires_grad=True)
y = x+2
z = torch.mean(torch.pow(y, 2))
lr = 1e-3
y.register_hook(print_grad)
z.backward()
x.data -= lr*x.grad.data

tensor([[2.9283],
        [1.0821]])


In [125]:
torch.sign(torch.randn(5))

tensor([-1., -1., -1.,  1., -1.])

In [130]:
torch.Tensor([3]).repeat(3)

tensor([3., 3., 3.])

In [7]:
import INN
import torch

model = INN.Sequential(INN.Nonlinear(3, method='RealNVP'),
                       INN.BatchNorm1d(3),
                       INN.Linear(3))
model.eval()

x = torch.Tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

y, logp, logdet = model(x)
print(y)

x_hat = model.inverse(y)
print(x_hat)

tensor([[ -4.9253,   1.0349,  -0.1721],
        [-18.1465,   5.9512,  -2.1945],
        [-29.2788,  10.0235,  -2.2862]], grad_fn=<MmBackward>)
tensor([[1.0000, 2.0000, 3.0000],
        [4.0000, 5.0000, 6.0000],
        [7.0000, 8.0000, 9.0000]], grad_fn=<AddBackward0>)


In [8]:
import INN
import torch

model = INN.ResizeFeatures(feature_in=3, feature_out=1)

x = torch.Tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

y, logp, logdet = model(x)
print(y)

x_hat = model.inverse(y)
print(x_hat)

tensor([[1.],
        [4.],
        [7.]])
tensor([[ 1.0000,  1.5800, -0.6237],
        [ 4.0000,  0.5238,  0.3988],
        [ 7.0000,  1.0111, -0.0900]])


In [12]:
import INN
import torch

model = INN.BatchNorm1d(3)
model.eval()
model.running_var = torch.abs(torch.randn(3))
model.running_mean = torch.abs(torch.randn(3))

x = torch.Tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

y, logp, logdet = model(x)
print(y)

x_hat = model.inverse(y)
print(x_hat)

tensor([[-1.3197,  1.3629,  0.8760],
        [ 2.3425,  4.4854,  3.7336],
        [ 6.0047,  7.6079,  6.5912]])
tensor([[1.0000, 2.0000, 3.0000],
        [4.0000, 5.0000, 6.0000],
        [7.0000, 8.0000, 9.0000]])


In [17]:
model.__getattr__('running_var')

tensor([0.6710, 0.9231, 1.1021])

In [20]:
model['running_var']

TypeError: 'BatchNorm1d' object is not subscriptable

In [223]:
def custom_weight_hook(self, input):
    # 定义hook，在运行之前更新weight
    # 在实际的权重上添加噪声
    self.weight = self.x + self.noise_level * torch.randn((self.in_features, self.in_features))

class NoiseLinear(nn.Linear):
    def __init__(self, dim_in, dim_out, noise_level=0.1):
        super(NoiseLinear, self).__init__(dim_in, dim_out, bias=False)
        self.noise_level = noise_level
        
        # 删除默认的weight，并注册一个buffer缓冲，作为weight
        del self.weight
        
        # 定义实际要训练的变量
        self.x = nn.Parameter(torch.ones((self.in_features, self.in_features)))
        # 注册一个forward_pre_hook，将在每次forward之前运行
        self.register_forward_pre_hook(self.custom_weight_hook)
    
    def custom_weight_hook(self, module, inputs):
        # 定义hook，在运行之前更新weight
        # 在实际的权重上添加噪声
        print(*inputs)
        self.weight = self.x + self.noise_level * torch.randn((self.in_features, self.in_features))
        

In [224]:
model = NoiseLinear(3, 3)
x = torch.randn(4,3)

In [229]:
model(x)

tensor([[-0.5906, -2.2672,  2.1911],
        [-0.4017,  1.6780, -1.4202],
        [-1.0896,  0.7093, -0.8677],
        [ 0.4006,  0.6941, -1.0644]])


tensor([[-0.8000, -0.6525, -0.6708],
        [-0.0775, -0.1151, -0.2130],
        [-1.2538, -1.2189, -1.3295],
        [ 0.0807, -0.0026,  0.0692]], grad_fn=<MmBackward>)

In [222]:
NoiseLinear.forward(model, x)

tensor([[-0.4075, -0.6115, -0.6070],
        [-1.5189, -1.8431, -1.6411],
        [ 1.0499,  0.7758,  0.8983],
        [ 0.3708,  0.1679,  0.3418]], grad_fn=<MmBackward>)