In [1]:
import iResNet

import torch
import torch.nn as nn
import torch.utils.data as data
import torch.optim as optim

import importlib
importlib.reload(iResNet)

<module 'iResNet' from '/home/yanbo/Research/Lab/eLIFE/iResNetLab/src/iResNet.py'>

In [12]:
model = iResNet.Sequential(iResNet.iResNetFCN(2, 2),
                           iResNet.iResNetFCN(2, 2, w=2),
                           iResNet.iResNetFCN(2, 2))
print(model)

Sequential(
  (0): iResNetFCN(
    (net): SNFCN(
      (g): Sequential(
        (0): Linear(in_features=2, out_features=16, bias=True)
        (1): GELU()
        (2): Linear(in_features=16, out_features=16, bias=True)
        (3): GELU()
        (4): Linear(in_features=16, out_features=2, bias=True)
      )
    )
    (noise): NormalDistribution()
  )
  (1): iResNetFCN(
    (net): SNFCN(
      (g): Sequential(
        (0): Linear(in_features=2, out_features=4, bias=True)
        (1): GELU()
        (2): Linear(in_features=4, out_features=4, bias=True)
        (3): GELU()
        (4): Linear(in_features=4, out_features=2, bias=True)
      )
    )
    (noise): NormalDistribution()
  )
  (2): iResNetFCN(
    (net): SNFCN(
      (g): Sequential(
        (0): Linear(in_features=2, out_features=16, bias=True)
        (1): GELU()
        (2): Linear(in_features=16, out_features=16, bias=True)
        (3): GELU()
        (4): Linear(in_features=16, out_features=2, bias=True)
      )
    )
    

In [13]:
x = torch.Tensor([[1,2], [3,4], [-3,1]])
x.requires_grad = True
model.train()

y, p, logdet = model(x)
y

tensor([[-0.5160,  1.8480],
        [ 0.4247,  3.6517],
        [-4.1846,  1.5245]], grad_fn=<SliceBackward>)

In [14]:
x = torch.Tensor([[1,2], [3,4], [-2, 1]])
x.requires_grad = True
model.eval()

y = model(x)
y

tensor([[-0.5160,  1.8480],
        [ 0.4247,  3.6517],
        [-3.0606,  1.3838]], grad_fn=<SliceBackward>)

In [15]:
model.inverse(y.detach())

tensor([[ 1.0000,  2.0000],
        [ 3.0000,  4.0000],
        [-2.0000,  1.0000]])